<?php
function mymodule_menu() {
  $items = array();
 
  $items['mymodule/page'] = array(
    'page callback' => 'mymodule_page',
	
    'access callback' => TRUE,
    'type' => MENU_CALLBACK,
  );
 
  $items['mymodule/%ctools_js'] = array(
    'page callback' => 'mymodule_callback',
    'page arguments' => array(1,2),
    'access callback' => TRUE,
    'type' => MENU_CALLBACK,
  );
 
  return $items;
}

//'page arguments' => array(3),

/**
 * Helper function to make a link.
 */
function _mymodule_make_link($link_text = '') {
  // Set a default value if no text in supplied.
  if (empty($link_text)) {
    $link_text = 'Magical Modal';
  }
 
 $rtn = '<div id="magical-modal-link">' . l($link_text.'1', 'mymodule/nojs/1', array('attributes' => array('class' => 'ctools-use-modal'))) . '</div>';
 $rtn .= '<div id="magical-modal-link">' . l($link_text.'2', 'mymodule/nojs/2', array('attributes' => array('class' => 'ctools-use-modal'))) . '</div>';
 $rtn .= '<div id="magical-modal-link">' . l($link_text.'3', 'mymodule/nojs/3', array('attributes' => array('class' => 'ctools-use-modal'))) . '</div>';
 return $rtn;
}


/**
 * An example page.
 */
function mymodule_page() {
  // Load the modal library and add the modal javascript.
  ctools_include('modal');
  ctools_modal_add_js();
  return _mymodule_make_link('Magical modal');
}



/**
 * Ajax menu callback.
 */
function mymodule_callback($ajax, $link) {
  if ($ajax) {
    ctools_include('ajax');
    ctools_include('modal');
 
    $form_state = array(
      'ajax' => TRUE,
      'title' => t('MyModule Modal Form '.$link),
    );
	global $mylink;
		$mylink =$link;
    // Use ctools to generate ajax instructions for the browser to create
    // a form in a modal popup.
    $output = ctools_modal_form_wrapper('mymodule_form', $form_state, $link);
    // If the form has been submitted, there may be additional instructions
    // such as dismissing the modal popup.
    if (!empty($form_state['ajax_commands'])) {
      $output = $form_state['ajax_commands'];
    }
 
    // Return the ajax instructions to the browser via ajax_render().
    print ajax_render($output);
    drupal_exit();
  }
  else {
    return drupal_get_form('mymodule_form', $form_state, $link);
  }
}



/**
 * Drupal form to be put in a modal.
 */
function mymodule_form($form, $form_state, $link) {
global $mylink;
$link = $mylink;
  $form['contact_information'] = array(
  '#markup' =>  t("For a high resolution version photograph please enter your details and we will respond within 24 hours to your request, thank you"),
);
 
  $form['firstname'] = array(
    '#type' => 'textfield',
    '#title' => t('First Name'),
  );
  $form['surname'] = array(
    '#type' => 'textfield',
    '#title' => t('Surname'),
  );
  $form['emailaddress'] = array(
    '#type' => 'textfield',
    '#title' => t('Email'),
  );
 
  $form['submit'] = array(
    '#type' => 'submit',
    '#value' => t('Submit'),
  );
 
  return $form;
}



/**
 * Drupal form submit handler.
 */
function mymodule_form_submit(&$form, &$form_state) {
 //save the details in db
 /*
 $last_request = db_insert('image_downloaded') 
	->fields(array(
	  'first_name' => $form_state['values']['firstname'],
	  'surname' => $form_state['values']['surname'],
	  'user_email' => $form_state['values']['emailaddress'],
	  'fileID' => 2,
	  'emailed' => 0,
	  'date_requested' => REQUEST_TIME,
	))
	->execute();
	*/

  $form_state['ajax_commands'][] = ctools_modal_command_dismiss();
 
  // Tell the browser to replace the old link with the new one.
  //$form_state['ajax_commands'][] = ajax_command_replace('#magical-modal-link', $link);
}